baseURL = "https://KaptajnBajer.github.io/CSS_F_Project/"
title = "With Subtle Notes of Dry Summer Rain"
description = "Er det nu også det?"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Kasper Brun"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/KaptajnBajer/CSS_F_Project"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

